server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/predicate/**            # 断言，路径相匹配的进行路由
            - After=2023-11-20T17:38:13.586918800+08:00[Asia/Shanghai]
            #            - name: My
            #              args:
            #                userType: diamond
            - My=gold
        #            - Cookie=username,Brian
        #            - Before=2024-04-09T22:32:40.424566300+08:00[Asia/Shanghai] #超过规定时间不可访问
        #            - Between=2024-04-09T22:32:40.424566300+08:00[Asia/Shanghai],2024-04-10T01:35:40.424566300+08:00[Asia/Shanghai] #在这个时间段内可访问
        #            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
        #            - Host=**.atguigu.com      # 请求头要有主机
        #            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
        #            - RemoteAddr=192.168.1.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
        #            - Method=GET,POST
        - id: pay_routh4 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
#            - Path=/XYZ/abc/{segment}
          filters:
            - My=atguigu
#            - RedirectTo=302, http://www.atgui.com
#            - SetPath=/pay/gateway/{segment}
#            - PrefixPath=/pay    #请求路径变为 PrefixPath+Path 浏览器访问时隐藏前缀，直接用path 就可以
#            - AddRequestHeader=X-Request-atguigu1, atguiguValue1
#            - AddRequestHeader=X-Request-atguigu2, atguiguValue2
#            - RemoveRequestHeader=sec-fetch-mode  #删除该请求头
#            - AddRequestParameter=customerId, 952701
#            - RemoveRequestParameter=customerName # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除